startDelaySeconds: 0
ssl: false
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  - "org.apache.spark:type=JvmMetrics,name=*"
  - "org.apache.spark:type=Worker,workerId=*"
  - "org.apache.spark:type=Master,name=*"
  - "org.apache.spark:type=ApplicationMetrics,name=*"
rules:
  - pattern: "org.apache.spark<type=JvmMetrics, name=(.+)><>Value"
    name: spark_jvm_$1
    type: GAUGE
