name: spark-mastodon-monitoring

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ../docker/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports: ["9090:9090"]
    networks: [ data_net ]

  grafana:
    image: grafana/grafana:10.4.5
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports: ["3000:3000"]
    volumes:
      - ../docker/monitoring/provisioning:/etc/grafana/provisioning:ro
      - ../docker/monitoring/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks: [ data_net ]

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    networks: [ data_net ]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    ports: ["8082:8080"]
    networks: [ data_net ]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

networks:
  data_net:
    external: true
